"""initial schema

Revision ID: 0339d76df33c
Revises: 
Create Date: 2026-08-20 17:10:51.151174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0339d76df33c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_def',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('data_type', sa.String(length=16), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('higher_is_better', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metric_version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_def_tenant_id'), 'metric_def', ['tenant_id'], unique=False)
    op.create_table('prompt',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('template_sha256', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'template_sha256', name='uq_prompt_template')
    )
    op.create_index(op.f('ix_prompt_tenant_id'), 'prompt', ['tenant_id'], unique=False)
    op.create_table('tombstone',
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('call_id', sa.String(length=128), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('tenant_id', 'call_id')
    )
    op.create_table('call',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('external_call_id', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('environment', sa.String(length=16), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=True),
    sa.Column('engine', sa.String(length=16), nullable=True),
    sa.Column('carrier', sa.String(length=32), nullable=True),
    sa.Column('stt_provider', sa.String(length=64), nullable=True),
    sa.Column('llm_provider', sa.String(length=64), nullable=True),
    sa.Column('tts_provider', sa.String(length=64), nullable=True),
    sa.Column('voice', sa.String(length=64), nullable=True),
    sa.Column('campaign_id', sa.String(length=128), nullable=True),
    sa.Column('prompt_id', sa.String(length=36), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('audio_t0_offset_s', sa.Float(), nullable=True),
    sa.Column('audio_t0_epoch_ns', sa.Integer(), nullable=True),
    sa.Column('channel_map', sa.JSON(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('terminal_reason', sa.String(length=64), nullable=True),
    sa.Column('hangup_by', sa.String(length=16), nullable=True),
    sa.Column('stream_duration_s', sa.Float(), nullable=True),
    sa.Column('cost_llm', sa.Float(), nullable=True),
    sa.Column('cost_stt', sa.Float(), nullable=True),
    sa.Column('cost_tts', sa.Float(), nullable=True),
    sa.Column('cost_total', sa.Float(), nullable=True),
    sa.Column('cost_currency', sa.String(length=8), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('tokens_cached', sa.Integer(), nullable=True),
    sa.Column('tts_chars', sa.Integer(), nullable=True),
    sa.Column('tts_chars_cut', sa.Integer(), nullable=True),
    sa.Column('stt_seconds', sa.Float(), nullable=True),
    sa.Column('stt_segments_heard', sa.Integer(), nullable=True),
    sa.Column('stt_segments_overheard', sa.Integer(), nullable=True),
    sa.Column('stt_segments_dropped', sa.Integer(), nullable=True),
    sa.Column('span_dropped_events', sa.Integer(), nullable=True),
    sa.Column('unattributed_spans', sa.Integer(), nullable=True),
    sa.Column('service_instance_id', sa.String(length=64), nullable=True),
    sa.Column('spans_complete', sa.Boolean(), nullable=False),
    sa.Column('media_ready', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bookmarked', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('app_version', sa.String(length=64), nullable=True),
    sa.Column('metric_version', sa.Integer(), nullable=True),
    sa.Column('adapter_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'external_call_id', name='uq_call_external')
    )
    op.create_index('ix_call_status_activity', 'call', ['status', 'last_activity_at'], unique=False)
    op.create_index('ix_call_tenant_env_started', 'call', ['tenant_id', 'environment', 'started_at'], unique=False)
    op.create_index(op.f('ix_call_tenant_id'), 'call', ['tenant_id'], unique=False)
    op.create_table('annotation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('call_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('source', sa.String(length=48), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('body', sa.JSON(), nullable=True),
    sa.Column('body_sha256', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['call.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id', 'kind', 'source', 'body_sha256', name='uq_annotation_body')
    )
    op.create_index(op.f('ix_annotation_tenant_id'), 'annotation', ['tenant_id'], unique=False)
    op.create_table('event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('call_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('span_id', sa.String(length=64), nullable=True),
    sa.Column('parent_span_id', sa.String(length=64), nullable=True),
    sa.Column('turn_id', sa.String(length=160), nullable=True),
    sa.Column('t_offset_s', sa.Float(), nullable=True),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('attrs', sa.JSON(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('content_kind', sa.String(length=24), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['call.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_call_span', 'event', ['call_id', 'span_id'], unique=False)
    op.create_index('ix_event_call_t', 'event', ['call_id', 't_offset_s'], unique=False)
    op.create_index(op.f('ix_event_tenant_id'), 'event', ['tenant_id'], unique=False)
    op.create_table('ingest_run',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('call_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('app_version', sa.String(length=64), nullable=True),
    sa.Column('metric_version', sa.Integer(), nullable=True),
    sa.Column('adapter_version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['call.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingest_run_tenant_id'), 'ingest_run', ['tenant_id'], unique=False)
    op.create_index('ix_ingestrun_call_metric', 'ingest_run', ['call_id', 'metric_version'], unique=False)
    op.create_table('label',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('call_id', sa.String(length=36), nullable=False),
    sa.Column('turn_id', sa.String(length=160), nullable=True),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('value', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['call.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_label_tenant_id'), 'label', ['tenant_id'], unique=False)
    op.create_table('media',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('call_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('uri', sa.String(length=1024), nullable=True),
    sa.Column('peaks', sa.LargeBinary(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('bytes', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=64), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['call.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id', 'kind', 'sha256', name='uq_media_kind_sha')
    )
    op.create_index(op.f('ix_media_tenant_id'), 'media', ['tenant_id'], unique=False)
    op.create_table('metric',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('call_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('value_num', sa.Float(), nullable=True),
    sa.Column('value_text', sa.String(length=128), nullable=True),
    sa.Column('samples', sa.JSON(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=True),
    sa.Column('metric_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['call.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id', 'name', 'metric_version', name='uq_metric_name_version')
    )
    op.create_index(op.f('ix_metric_tenant_id'), 'metric', ['tenant_id'], unique=False)
    op.create_index('ix_metric_tenant_name_value', 'metric', ['tenant_id', 'name', 'value_num'], unique=False)
    op.create_table('raw_fragment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('call_id', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_gz', sa.LargeBinary(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['call.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_fragment_tenant_id'), 'raw_fragment', ['tenant_id'], unique=False)
    op.create_index('ix_rawfragment_call_batch_seq', 'raw_fragment', ['call_id', 'batch_id', 'seq'], unique=False)
    op.create_table('turn',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('call_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('turn_id', sa.String(length=160), nullable=True),
    sa.Column('trigger', sa.String(length=16), nullable=True),
    sa.Column('interrupted', sa.Boolean(), nullable=True),
    sa.Column('abandoned', sa.Boolean(), nullable=True),
    sa.Column('stt_final_at', sa.Float(), nullable=True),
    sa.Column('committed_at', sa.Float(), nullable=True),
    sa.Column('llm_first_token_at', sa.Float(), nullable=True),
    sa.Column('tts_start_at', sa.Float(), nullable=True),
    sa.Column('tts_first_audio_at', sa.Float(), nullable=True),
    sa.Column('caller_utt_end_s', sa.Float(), nullable=True),
    sa.Column('agent_utt_start_s', sa.Float(), nullable=True),
    sa.Column('response_latency_ms', sa.Float(), nullable=True),
    sa.Column('stt_lag_ms', sa.Float(), nullable=True),
    sa.Column('endpointing_ms', sa.Float(), nullable=True),
    sa.Column('llm_ttft_ms', sa.Float(), nullable=True),
    sa.Column('assembly_ms', sa.Float(), nullable=True),
    sa.Column('tts_ttfb_ms', sa.Float(), nullable=True),
    sa.Column('playout_ms', sa.Float(), nullable=True),
    sa.Column('unattributed_ms', sa.Float(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('stt_confidence', sa.Float(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('tokens_cached', sa.Integer(), nullable=True),
    sa.Column('finish_reason', sa.String(length=32), nullable=True),
    sa.Column('tts_chars', sa.Integer(), nullable=True),
    sa.Column('tts_chars_cut', sa.Integer(), nullable=True),
    sa.Column('cut_reason', sa.String(length=16), nullable=True),
    sa.Column('tts_span_present', sa.Boolean(), nullable=True),
    sa.Column('caller_transcript', sa.Text(), nullable=True),
    sa.Column('llm_raw', sa.Text(), nullable=True),
    sa.Column('llm_spoken', sa.Text(), nullable=True),
    sa.Column('metric_version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['call.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id', 'turn_index', name='uq_turn_index')
    )
    op.create_index(op.f('ix_turn_tenant_id'), 'turn', ['tenant_id'], unique=False)
    op.create_table('utterance',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('call_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('t_start_s', sa.Float(), nullable=False),
    sa.Column('t_end_s', sa.Float(), nullable=False),
    sa.Column('metric_version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['call.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_utterance_call_start', 'utterance', ['call_id', 't_start_s'], unique=False)
    op.create_index(op.f('ix_utterance_tenant_id'), 'utterance', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utterance_tenant_id'), table_name='utterance')
    op.drop_index('ix_utterance_call_start', table_name='utterance')
    op.drop_table('utterance')
    op.drop_index(op.f('ix_turn_tenant_id'), table_name='turn')
    op.drop_table('turn')
    op.drop_index('ix_rawfragment_call_batch_seq', table_name='raw_fragment')
    op.drop_index(op.f('ix_raw_fragment_tenant_id'), table_name='raw_fragment')
    op.drop_table('raw_fragment')
    op.drop_index('ix_metric_tenant_name_value', table_name='metric')
    op.drop_index(op.f('ix_metric_tenant_id'), table_name='metric')
    op.drop_table('metric')
    op.drop_index(op.f('ix_media_tenant_id'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_label_tenant_id'), table_name='label')
    op.drop_table('label')
    op.drop_index('ix_ingestrun_call_metric', table_name='ingest_run')
    op.drop_index(op.f('ix_ingest_run_tenant_id'), table_name='ingest_run')
    op.drop_table('ingest_run')
    op.drop_index(op.f('ix_event_tenant_id'), table_name='event')
    op.drop_index('ix_event_call_t', table_name='event')
    op.drop_index('ix_event_call_span', table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_annotation_tenant_id'), table_name='annotation')
    op.drop_table('annotation')
    op.drop_index(op.f('ix_call_tenant_id'), table_name='call')
    op.drop_index('ix_call_tenant_env_started', table_name='call')
    op.drop_index('ix_call_status_activity', table_name='call')
    op.drop_table('call')
    op.drop_table('tombstone')
    op.drop_index(op.f('ix_prompt_tenant_id'), table_name='prompt')
    op.drop_table('prompt')
    op.drop_index(op.f('ix_metric_def_tenant_id'), table_name='metric_def')
    op.drop_table('metric_def')
    # ### end Alembic commands ###
